
GET http://localhost:8080/api/pokedex
Content-Type: application/json

###


GET http://localhost:8080/api/pokedex/name/?name=bulbasaur
Content-Type: application/json

###


GET http://localhost:8080/api/pokedex/number/?number=2
Content-Type: application/json

###


GET http://localhost:8080/api/pokedex/test
Content-Type: application/json

###

GET http://localhost:8080/api/typings
Content-Type: application/json

###

GET http://localhost:8080/api/type/?name=Water
Content-Type: application/json


###
GET http://localhost:8080/api/fastMove/?name=Acid
Content-Type: application/json

###
GET http://localhost:8080/api/fastMoves
Content-Type: application/json

###
GET http://localhost:8080/api/chargedMoves
Content-Type: application/json

###
GET http://localhost:8080/api/chargedMove/?=Ancient Power
Content-Type: application/json