
GET http://localhost:8080/api/pokedex
Content-Type: application/json

###

GET http://localhost:8080/api/typings
Content-Type: application/json

###

GET http://localhost:8080/api/type/?name=Water
Content-Type: application/json